name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y g++
          sudo apt install -y cmake

      - name: Restore OpenCV and Ceres Solver
        id: restore-opencv-ceres-solver
        uses: actions/cache/restore@v4
        with:
          path: |
            opencv-4.5.1
            ceres-solver-2.0.0
          key: builds

      - name: Build OpenCV 4.5.1
        if: steps.restore-opencv-ceres-solver.outputs.cache-hit != 'true'
        run: sudo bash .github/scripts/install_opencv451.sh;

      - name: Build Ceres Solver
        if: steps.restore-opencv-ceres-solver.outputs.cache-hit != 'true'
        run: sudo bash .github/scripts/install_ceres_solver200.sh

      - name: Cache OpenCV and Ceres Solver
        if: steps.restore-opencv-ceres-solver.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            opencv-4.5.1
            ceres-solver-2.0.0
          key: ${{ steps.restore-opencv-ceres-solver.outputs.cache-primary-key }}

      - name: Install Eigen 3
        run: sudo bash .github/scripts/install_eigen3.sh

      - name: Install OpenCV 4.5.1 and Ceres Solver
        run: |
          cd opencv-4.5.1/build
          sudo make install
          cd ../..
          cd ceres-solver-2.0.0/build
          sudo make install

#      - name: Install OpenCL CPU driver
#        run: sudo bash .github/scripts/install_intel_opencl.sh;

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 8

      - name: test_depth_maps_pm
        working-directory: ${{github.workspace}}
        run: ./build/test_depth_maps_pm

      - uses: actions/upload-artifact@v4
        with:
          path: data/debug/test_depth_maps_pm/
